#!/bin/sh

# Set these paths appropriately

BIN=/Users/lillioetting/Documents/cs124/project6/bin
CMD=/Users/lillioetting/Documents/cs124/project6/cmd
LIB=/Users/lillioetting/Documents/cs124/project6/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
