#!/bin/sh

# Set these paths appropriately

BIN=/Users/lillioetting/Documents/cs124/project6/bin
CMD=/Users/lillioetting/Documents/cs124/project6/cmd
LIB=/Users/lillioetting/Documents/cs124/project6/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
