#!/bin/sh

# Set these paths appropriately

BIN=/Users/lillioetting/Documents/cs124/project6/bin
CMD=/Users/lillioetting/Documents/cs124/project6/cmd
LIB=/Users/lillioetting/Documents/cs124/project6/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
