#!/bin/sh

# Set these paths appropriately

BIN=/Users/lillioetting/Documents/cs124/project6/bin
CMD=/Users/lillioetting/Documents/cs124/project6/cmd
LIB=/Users/lillioetting/Documents/cs124/project6/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
